# This is a basic workflow to help you get started with Actions

name: getting start

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: log in the pre-build disc space
         run: df
         
         - name: Checkout main github
           uses: actions/checkout@v2
           
            -name: Set up JDK 1.8
             uses: actions/setup-java@v1
             with: java -version 1.8
       
          - name: Run a one-line script
             run: sh ./git-Actions-script.sh
        
          - name: Build your jakarta web app with haven
             run: echo mvn -B package --filepom.xml
        
          - name: Build the native Andriod app
             run: |
              echo here is the ANDRIOD_SDK_ROOT
	      echo $ANDRIOD_SDK_ROOT
           
          - name: Run Selenium tests
             run: |
              echo the SELENIUM_JAR_PATH
	      echo $SELENIUM_JAR_PATH
           
          - name: Log build tool versions 
	     run: |
	     git --version
             mvn --version
             ant --version
             gradle --version
          
          
       - name: log out the pre-build disc space
         run: df
           
		
        
         

        
      
